#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalManagementSoftware.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Centerport_Medical")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::MedicalManagementSoftware.Properties.Settings.Default.Centerport_MedicalConnectionString5, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_userLevel")]
		public ISingleResult<sp_userLevelResult> sp_userLevel()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_userLevelResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_loginifNotHead")]
		public ISingleResult<sp_loginifNotHeadResult> sp_loginifNotHead([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(20)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<sp_loginifNotHeadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_updateName")]
		public int sp_updateName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string middlename, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string birthdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string address_1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contact_1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string employer, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string position, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string passport_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string seamansbook_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sirb, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(50)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lastname, firstname, middlename, birthdate, gender, address_1, contact_1, employer, position, passport_no, seamansbook_no, sirb, iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Seabase_MedHistory2")]
		public ISingleResult<sp_Seabase_MedHistory2Result> sp_Seabase_MedHistory2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(20)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<sp_Seabase_MedHistory2Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_krpan")]
		public ISingleResult<sp_krpanResult> sp_krpan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(MAX)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<sp_krpanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_countKrPan")]
		public ISingleResult<sp_countKrPanResult> sp_countKrPan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(1)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<sp_countKrPanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_krpan_report")]
		public ISingleResult<sp_krpan_reportResult> sp_krpan_report([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(MAX)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<sp_krpan_reportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_update_krpan")]
		public int sp_update_krpan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID1", DbType="VarChar(MAX)")] string iD1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID2", DbType="VarChar(MAX)")] string iD2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID3", DbType="VarChar(MAX)")] string iD3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID4", DbType="VarChar(MAX)")] string iD4, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID5", DbType="VarChar(MAX)")] string iD5, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID6", DbType="VarChar(MAX)")] string iD6, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID7", DbType="VarChar(MAX)")] string iD7, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID8", DbType="VarChar(MAX)")] string iD8, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID9", DbType="VarChar(MAX)")] string iD9, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID10", DbType="VarChar(MAX)")] string iD10)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD1, iD2, iD3, iD4, iD5, iD6, iD7, iD8, iD9, iD10);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Seabase_Mer1_Sub")]
		public ISingleResult<sp_Seabase_Mer1_SubResult> sp_Seabase_Mer1_Sub([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(20)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<sp_Seabase_Mer1_SubResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateLabExtra")]
		public int UpdateLabExtra([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MedTechName", DbType="VarChar(MAX)")] string medTechName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MedTechLicense", DbType="VarChar(MAX)")] string medTechLicense, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PathologistName", DbType="VarChar(MAX)")] string pathologistName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PathologistLicense", DbType="VarChar(MAX)")] string pathologistLicense, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string psa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string tumorOthers, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AntiHBS", DbType="VarChar(MAX)")] string antiHBS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HBsAG", DbType="VarChar(MAX)")] string hBsAG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ImmunologicalOthers", DbType="VarChar(MAX)")] string immunologicalOthers, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecNo", DbType="VarChar(MAX)")] string recNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), medTechName, medTechLicense, pathologistName, pathologistLicense, psa, tumorOthers, antiHBS, hBsAG, immunologicalOthers, recNo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_User")]
		public ISingleResult<sp_UserResult> sp_User()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_UserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CenterportAccounting_ProductListing")]
		public ISingleResult<CenterportAccounting_ProductListingResult> CenterportAccounting_ProductListing()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CenterportAccounting_ProductListingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_login")]
		public ISingleResult<sp_loginResult> sp_login([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SystmType", DbType="VarChar(50)")] string systmType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password, systmType);
			return ((ISingleResult<sp_loginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USER_INSERT")]
		public ISingleResult<USER_INSERTResult> USER_INSERT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fullname", DbType="VarChar(100)")] string fullname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(100)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(100)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Userlevel", DbType="VarChar(20)")] string userlevel)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fullname, username, password, userlevel);
			return ((ISingleResult<USER_INSERTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USER_UPDATE")]
		public ISingleResult<USER_UPDATEResult> USER_UPDATE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fullname", DbType="VarChar(100)")] string fullname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(100)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(100)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Userlevel", DbType="VarChar(20)")] string userlevel, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remark", DbType="VarChar(20)")] string remark)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cn, fullname, username, password, userlevel, remark);
			return ((ISingleResult<USER_UPDATEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MedicalPatientList")]
		public ISingleResult<MedicalPatientListResult> MedicalPatientList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MedicalPatientListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MedicalImmunologyTestSAVE")]
		public int MedicalImmunologyTestSAVE(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LaboratoryNo", DbType="VarChar(100)")] string laboratoryNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Papin", DbType="VarChar(100)")] string papin, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string psa, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Other", DbType="VarChar(100)")] string other, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HBsAg", DbType="VarChar(100)")] string hBsAg, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RPR", DbType="VarChar(100)")] string rPR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AntiHBS", DbType="VarChar(100)")] string antiHBS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AntiHBSResult", DbType="VarChar(100)")] string antiHBSResult, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MedTech", DbType="VarChar(100)")] string medTech, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MedTechLicense", DbType="VarChar(100)")] string medTechLicense, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pathologist", DbType="VarChar(100)")] string pathologist, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PathologistLicense", DbType="VarChar(100)")] string pathologistLicense, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResultDate", DbType="VarChar(100)")] string resultDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string otherName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string otherRefValue, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string cutOff)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), laboratoryNo, papin, psa, other, hBsAg, rPR, antiHBS, antiHBSResult, medTech, medTechLicense, pathologist, pathologistLicense, resultDate, otherName, otherRefValue, cutOff);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MedicalImmunologyTestSearch")]
		public ISingleResult<MedicalImmunologyTestSearchResult> MedicalImmunologyTestSearch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Papin", DbType="VarChar(50)")] string papin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), papin);
			return ((ISingleResult<MedicalImmunologyTestSearchResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_userLevelResult
	{
		
		private int _cn;
		
		private string _Description;
		
		public sp_userLevelResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(254)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	public partial class sp_loginifNotHeadResult
	{
		
		private int _cn;
		
		private string _Fullname;
		
		private string _Username;
		
		private string _Password;
		
		private System.Nullable<bool> _Remark;
		
		private string _Description;
		
		public sp_loginifNotHeadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="VarChar(254)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(254)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(254)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="Bit")]
		public System.Nullable<bool> Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(254)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	public partial class sp_Seabase_MedHistory2Result
	{
		
		private int _cn;
		
		private string _resultid;
		
		private string _column1;
		
		private string _column2;
		
		private string _column3;
		
		private string _column4;
		
		private string _column5;
		
		private string _column6;
		
		private string _column7;
		
		private string _column7_comment;
		
		private string _column8;
		
		private string _column8_comment;
		
		private string _column1_comment;
		
		private string _column2_comment;
		
		private string _column3_comment;
		
		private string _column4_comment;
		
		private string _column5_comment;
		
		private string _column6_comment;
		
		public sp_Seabase_MedHistory2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultid", DbType="VarChar(254)")]
		public string resultid
		{
			get
			{
				return this._resultid;
			}
			set
			{
				if ((this._resultid != value))
				{
					this._resultid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column1", DbType="VarChar(254)")]
		public string column1
		{
			get
			{
				return this._column1;
			}
			set
			{
				if ((this._column1 != value))
				{
					this._column1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column2", DbType="VarChar(254)")]
		public string column2
		{
			get
			{
				return this._column2;
			}
			set
			{
				if ((this._column2 != value))
				{
					this._column2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column3", DbType="VarChar(254)")]
		public string column3
		{
			get
			{
				return this._column3;
			}
			set
			{
				if ((this._column3 != value))
				{
					this._column3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column4", DbType="VarChar(254)")]
		public string column4
		{
			get
			{
				return this._column4;
			}
			set
			{
				if ((this._column4 != value))
				{
					this._column4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column5", DbType="VarChar(254)")]
		public string column5
		{
			get
			{
				return this._column5;
			}
			set
			{
				if ((this._column5 != value))
				{
					this._column5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column6", DbType="VarChar(254)")]
		public string column6
		{
			get
			{
				return this._column6;
			}
			set
			{
				if ((this._column6 != value))
				{
					this._column6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column7", DbType="VarChar(254)")]
		public string column7
		{
			get
			{
				return this._column7;
			}
			set
			{
				if ((this._column7 != value))
				{
					this._column7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column7_comment", DbType="VarChar(254)")]
		public string column7_comment
		{
			get
			{
				return this._column7_comment;
			}
			set
			{
				if ((this._column7_comment != value))
				{
					this._column7_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column8", DbType="VarChar(254)")]
		public string column8
		{
			get
			{
				return this._column8;
			}
			set
			{
				if ((this._column8 != value))
				{
					this._column8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column8_comment", DbType="VarChar(254)")]
		public string column8_comment
		{
			get
			{
				return this._column8_comment;
			}
			set
			{
				if ((this._column8_comment != value))
				{
					this._column8_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column1_comment", DbType="VarChar(254)")]
		public string column1_comment
		{
			get
			{
				return this._column1_comment;
			}
			set
			{
				if ((this._column1_comment != value))
				{
					this._column1_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column2_comment", DbType="VarChar(254)")]
		public string column2_comment
		{
			get
			{
				return this._column2_comment;
			}
			set
			{
				if ((this._column2_comment != value))
				{
					this._column2_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column3_comment", DbType="VarChar(254)")]
		public string column3_comment
		{
			get
			{
				return this._column3_comment;
			}
			set
			{
				if ((this._column3_comment != value))
				{
					this._column3_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column4_comment", DbType="VarChar(254)")]
		public string column4_comment
		{
			get
			{
				return this._column4_comment;
			}
			set
			{
				if ((this._column4_comment != value))
				{
					this._column4_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column5_comment", DbType="VarChar(254)")]
		public string column5_comment
		{
			get
			{
				return this._column5_comment;
			}
			set
			{
				if ((this._column5_comment != value))
				{
					this._column5_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column6_comment", DbType="VarChar(254)")]
		public string column6_comment
		{
			get
			{
				return this._column6_comment;
			}
			set
			{
				if ((this._column6_comment != value))
				{
					this._column6_comment = value;
				}
			}
		}
	}
	
	public partial class sp_krpanResult
	{
		
		private int _cn;
		
		private string _Resultid;
		
		private string _BloodDisorder;
		
		private string _MentalDisorder;
		
		private string _Cardiovascular;
		
		private string _CircumferenceChest;
		
		private string _Infection;
		
		private string _NervousSystem;
		
		private string _Digestive;
		
		private string _Liver;
		
		private string _Anemia;
		
		private string _UrineSyphilisis;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		public sp_krpanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultid", DbType="VarChar(MAX)")]
		public string Resultid
		{
			get
			{
				return this._Resultid;
			}
			set
			{
				if ((this._Resultid != value))
				{
					this._Resultid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodDisorder", DbType="VarChar(MAX)")]
		public string BloodDisorder
		{
			get
			{
				return this._BloodDisorder;
			}
			set
			{
				if ((this._BloodDisorder != value))
				{
					this._BloodDisorder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MentalDisorder", DbType="VarChar(MAX)")]
		public string MentalDisorder
		{
			get
			{
				return this._MentalDisorder;
			}
			set
			{
				if ((this._MentalDisorder != value))
				{
					this._MentalDisorder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cardiovascular", DbType="VarChar(MAX)")]
		public string Cardiovascular
		{
			get
			{
				return this._Cardiovascular;
			}
			set
			{
				if ((this._Cardiovascular != value))
				{
					this._Cardiovascular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CircumferenceChest", DbType="VarChar(MAX)")]
		public string CircumferenceChest
		{
			get
			{
				return this._CircumferenceChest;
			}
			set
			{
				if ((this._CircumferenceChest != value))
				{
					this._CircumferenceChest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Infection", DbType="VarChar(MAX)")]
		public string Infection
		{
			get
			{
				return this._Infection;
			}
			set
			{
				if ((this._Infection != value))
				{
					this._Infection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NervousSystem", DbType="VarChar(MAX)")]
		public string NervousSystem
		{
			get
			{
				return this._NervousSystem;
			}
			set
			{
				if ((this._NervousSystem != value))
				{
					this._NervousSystem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Digestive", DbType="VarChar(MAX)")]
		public string Digestive
		{
			get
			{
				return this._Digestive;
			}
			set
			{
				if ((this._Digestive != value))
				{
					this._Digestive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Liver", DbType="VarChar(MAX)")]
		public string Liver
		{
			get
			{
				return this._Liver;
			}
			set
			{
				if ((this._Liver != value))
				{
					this._Liver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anemia", DbType="VarChar(MAX)")]
		public string Anemia
		{
			get
			{
				return this._Anemia;
			}
			set
			{
				if ((this._Anemia != value))
				{
					this._Anemia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrineSyphilisis", DbType="VarChar(MAX)")]
		public string UrineSyphilisis
		{
			get
			{
				return this._UrineSyphilisis;
			}
			set
			{
				if ((this._UrineSyphilisis != value))
				{
					this._UrineSyphilisis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
	}
	
	public partial class sp_countKrPanResult
	{
		
		private System.Nullable<int> _Column1;
		
		public sp_countKrPanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class sp_krpan_reportResult
	{
		
		private int _cn;
		
		private string _Resultid;
		
		private string _BloodDisorder;
		
		private string _MentalDisorder;
		
		private string _Cardiovascular;
		
		private string _CircumferenceChest;
		
		private string _Infection;
		
		private string _NervousSystem;
		
		private string _Digestive;
		
		private string _Liver;
		
		private string _Anemia;
		
		private string _UrineSyphilisis;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		public sp_krpan_reportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultid", DbType="VarChar(MAX)")]
		public string Resultid
		{
			get
			{
				return this._Resultid;
			}
			set
			{
				if ((this._Resultid != value))
				{
					this._Resultid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodDisorder", DbType="VarChar(MAX)")]
		public string BloodDisorder
		{
			get
			{
				return this._BloodDisorder;
			}
			set
			{
				if ((this._BloodDisorder != value))
				{
					this._BloodDisorder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MentalDisorder", DbType="VarChar(MAX)")]
		public string MentalDisorder
		{
			get
			{
				return this._MentalDisorder;
			}
			set
			{
				if ((this._MentalDisorder != value))
				{
					this._MentalDisorder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cardiovascular", DbType="VarChar(MAX)")]
		public string Cardiovascular
		{
			get
			{
				return this._Cardiovascular;
			}
			set
			{
				if ((this._Cardiovascular != value))
				{
					this._Cardiovascular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CircumferenceChest", DbType="VarChar(MAX)")]
		public string CircumferenceChest
		{
			get
			{
				return this._CircumferenceChest;
			}
			set
			{
				if ((this._CircumferenceChest != value))
				{
					this._CircumferenceChest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Infection", DbType="VarChar(MAX)")]
		public string Infection
		{
			get
			{
				return this._Infection;
			}
			set
			{
				if ((this._Infection != value))
				{
					this._Infection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NervousSystem", DbType="VarChar(MAX)")]
		public string NervousSystem
		{
			get
			{
				return this._NervousSystem;
			}
			set
			{
				if ((this._NervousSystem != value))
				{
					this._NervousSystem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Digestive", DbType="VarChar(MAX)")]
		public string Digestive
		{
			get
			{
				return this._Digestive;
			}
			set
			{
				if ((this._Digestive != value))
				{
					this._Digestive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Liver", DbType="VarChar(MAX)")]
		public string Liver
		{
			get
			{
				return this._Liver;
			}
			set
			{
				if ((this._Liver != value))
				{
					this._Liver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anemia", DbType="VarChar(MAX)")]
		public string Anemia
		{
			get
			{
				return this._Anemia;
			}
			set
			{
				if ((this._Anemia != value))
				{
					this._Anemia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrineSyphilisis", DbType="VarChar(MAX)")]
		public string UrineSyphilisis
		{
			get
			{
				return this._UrineSyphilisis;
			}
			set
			{
				if ((this._UrineSyphilisis != value))
				{
					this._UrineSyphilisis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
	}
	
	public partial class sp_Seabase_Mer1_SubResult
	{
		
		private string _lastname;
		
		private string _firstname;
		
		private string _middlename;
		
		private string _address_1;
		
		private string _position;
		
		private string _marital_status;
		
		private string _gender;
		
		private string _birthdate;
		
		private string _place_of_birth;
		
		private string _employer;
		
		private string _passport_no;
		
		private string _seamansbook_no;
		
		private string _nationality;
		
		private string _religion;
		
		private string _designation;
		
		private System.Data.Linq.Binary _picture;
		
		private string _resultid;
		
		private string _HEIGHT;
		
		private string _WEIGHT;
		
		private string _BP;
		
		private string _PULSE;
		
		private string _RESPIRATION;
		
		private string _BODY_BUILD;
		
		private string _FAR_OD_U;
		
		private string _FAR_OD_C;
		
		private string _FAR_OS_U;
		
		private string _FAR_OS_C;
		
		private string _NEAR_ODJ_U;
		
		private string _NEAR_ODJ_C;
		
		private string _NEAR_OSJ_U;
		
		private string _NEAR_OSJ_C;
		
		private string _ISHIHARA_U;
		
		private string _ISHIHARA_C;
		
		private string _HEARING_AD;
		
		private string _HEARING_AS;
		
		private string _CONVERSATIONAL_AS;
		
		private string _HEARING_RIGHT;
		
		private string _HEARING_LEFT;
		
		private string _CLARITY_OF_SPEECH;
		
		private string _BP_DIASTOLIC;
		
		private string _RHYTHM;
		
		private string _head_injury;
		
		private string _frequent_headaches;
		
		private string _frequent_dizziness;
		
		private string _fainting_spells;
		
		private string _insomnia;
		
		private string _depression;
		
		private string _trachoma;
		
		private string _deafness;
		
		private string _nose_throat_disorder;
		
		private string _tuberculosis;
		
		private string _other_lung_disorder;
		
		private string _high_blood_pressure;
		
		private string _heart_disease;
		
		private string _rheumatic_fever;
		
		private string _diabetes_mellitus;
		
		private string _other_endocrine_disorder;
		
		private string _cancer_tumor;
		
		private string _blood_disorders;
		
		private string _stomach_pain;
		
		private string _other_abdominal_disorder;
		
		private string _kidney_bladder_disorder;
		
		private string _back_injury;
		
		private string _genetic_hereditary;
		
		private string _sexually_transmit_disease;
		
		private string _asthma;
		
		private string _allergies;
		
		private string _gynecological_disorder;
		
		private string _operations;
		
		private string _operations_specify;
		
		private string _schistosomiasis;
		
		private string _last_menstrual_period;
		
		private string _allergies_specify;
		
		private string _other_abdominal_specify;
		
		private string _column1;
		
		private string _column2;
		
		private string _column3;
		
		private string _column4;
		
		private string _column5;
		
		private string _column6;
		
		private string _column7;
		
		private string _column7_comment;
		
		private string _column8;
		
		private string _column8_comment;
		
		private string _column1_comment;
		
		private string _column2_comment;
		
		private string _column3_comment;
		
		private string _column4_comment;
		
		private string _column5_comment;
		
		private string _column6_comment;
		
		private string _country;
		
		public sp_Seabase_Mer1_SubResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="VarChar(50)")]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this._lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="VarChar(50)")]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this._firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middlename", DbType="VarChar(50)")]
		public string middlename
		{
			get
			{
				return this._middlename;
			}
			set
			{
				if ((this._middlename != value))
				{
					this._middlename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_1", DbType="VarChar(100)")]
		public string address_1
		{
			get
			{
				return this._address_1;
			}
			set
			{
				if ((this._address_1 != value))
				{
					this._address_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(50)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this._position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marital_status", DbType="VarChar(10)")]
		public string marital_status
		{
			get
			{
				return this._marital_status;
			}
			set
			{
				if ((this._marital_status != value))
				{
					this._marital_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(10)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdate", DbType="VarChar(50)")]
		public string birthdate
		{
			get
			{
				return this._birthdate;
			}
			set
			{
				if ((this._birthdate != value))
				{
					this._birthdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_place_of_birth", DbType="VarChar(50)")]
		public string place_of_birth
		{
			get
			{
				return this._place_of_birth;
			}
			set
			{
				if ((this._place_of_birth != value))
				{
					this._place_of_birth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employer", DbType="VarChar(50)")]
		public string employer
		{
			get
			{
				return this._employer;
			}
			set
			{
				if ((this._employer != value))
				{
					this._employer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passport_no", DbType="VarChar(50)")]
		public string passport_no
		{
			get
			{
				return this._passport_no;
			}
			set
			{
				if ((this._passport_no != value))
				{
					this._passport_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seamansbook_no", DbType="VarChar(50)")]
		public string seamansbook_no
		{
			get
			{
				return this._seamansbook_no;
			}
			set
			{
				if ((this._seamansbook_no != value))
				{
					this._seamansbook_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality", DbType="VarChar(15)")]
		public string nationality
		{
			get
			{
				return this._nationality;
			}
			set
			{
				if ((this._nationality != value))
				{
					this._nationality = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_religion", DbType="VarChar(100)")]
		public string religion
		{
			get
			{
				return this._religion;
			}
			set
			{
				if ((this._religion != value))
				{
					this._religion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designation", DbType="VarChar(20)")]
		public string designation
		{
			get
			{
				return this._designation;
			}
			set
			{
				if ((this._designation != value))
				{
					this._designation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picture", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary picture
		{
			get
			{
				return this._picture;
			}
			set
			{
				if ((this._picture != value))
				{
					this._picture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultid", DbType="VarChar(254)")]
		public string resultid
		{
			get
			{
				return this._resultid;
			}
			set
			{
				if ((this._resultid != value))
				{
					this._resultid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEIGHT", DbType="VarChar(254)")]
		public string HEIGHT
		{
			get
			{
				return this._HEIGHT;
			}
			set
			{
				if ((this._HEIGHT != value))
				{
					this._HEIGHT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEIGHT", DbType="VarChar(254)")]
		public string WEIGHT
		{
			get
			{
				return this._WEIGHT;
			}
			set
			{
				if ((this._WEIGHT != value))
				{
					this._WEIGHT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BP", DbType="VarChar(254)")]
		public string BP
		{
			get
			{
				return this._BP;
			}
			set
			{
				if ((this._BP != value))
				{
					this._BP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PULSE", DbType="VarChar(254)")]
		public string PULSE
		{
			get
			{
				return this._PULSE;
			}
			set
			{
				if ((this._PULSE != value))
				{
					this._PULSE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESPIRATION", DbType="VarChar(254)")]
		public string RESPIRATION
		{
			get
			{
				return this._RESPIRATION;
			}
			set
			{
				if ((this._RESPIRATION != value))
				{
					this._RESPIRATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BODY_BUILD", DbType="VarChar(254)")]
		public string BODY_BUILD
		{
			get
			{
				return this._BODY_BUILD;
			}
			set
			{
				if ((this._BODY_BUILD != value))
				{
					this._BODY_BUILD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAR_OD_U", DbType="VarChar(254)")]
		public string FAR_OD_U
		{
			get
			{
				return this._FAR_OD_U;
			}
			set
			{
				if ((this._FAR_OD_U != value))
				{
					this._FAR_OD_U = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAR_OD_C", DbType="VarChar(254)")]
		public string FAR_OD_C
		{
			get
			{
				return this._FAR_OD_C;
			}
			set
			{
				if ((this._FAR_OD_C != value))
				{
					this._FAR_OD_C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAR_OS_U", DbType="VarChar(254)")]
		public string FAR_OS_U
		{
			get
			{
				return this._FAR_OS_U;
			}
			set
			{
				if ((this._FAR_OS_U != value))
				{
					this._FAR_OS_U = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAR_OS_C", DbType="VarChar(254)")]
		public string FAR_OS_C
		{
			get
			{
				return this._FAR_OS_C;
			}
			set
			{
				if ((this._FAR_OS_C != value))
				{
					this._FAR_OS_C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NEAR_ODJ_U", DbType="VarChar(254)")]
		public string NEAR_ODJ_U
		{
			get
			{
				return this._NEAR_ODJ_U;
			}
			set
			{
				if ((this._NEAR_ODJ_U != value))
				{
					this._NEAR_ODJ_U = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NEAR_ODJ_C", DbType="VarChar(254)")]
		public string NEAR_ODJ_C
		{
			get
			{
				return this._NEAR_ODJ_C;
			}
			set
			{
				if ((this._NEAR_ODJ_C != value))
				{
					this._NEAR_ODJ_C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NEAR_OSJ_U", DbType="VarChar(254)")]
		public string NEAR_OSJ_U
		{
			get
			{
				return this._NEAR_OSJ_U;
			}
			set
			{
				if ((this._NEAR_OSJ_U != value))
				{
					this._NEAR_OSJ_U = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NEAR_OSJ_C", DbType="VarChar(254)")]
		public string NEAR_OSJ_C
		{
			get
			{
				return this._NEAR_OSJ_C;
			}
			set
			{
				if ((this._NEAR_OSJ_C != value))
				{
					this._NEAR_OSJ_C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHIHARA_U", DbType="VarChar(254)")]
		public string ISHIHARA_U
		{
			get
			{
				return this._ISHIHARA_U;
			}
			set
			{
				if ((this._ISHIHARA_U != value))
				{
					this._ISHIHARA_U = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHIHARA_C", DbType="VarChar(254)")]
		public string ISHIHARA_C
		{
			get
			{
				return this._ISHIHARA_C;
			}
			set
			{
				if ((this._ISHIHARA_C != value))
				{
					this._ISHIHARA_C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEARING_AD", DbType="VarChar(254)")]
		public string HEARING_AD
		{
			get
			{
				return this._HEARING_AD;
			}
			set
			{
				if ((this._HEARING_AD != value))
				{
					this._HEARING_AD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEARING_AS", DbType="VarChar(254)")]
		public string HEARING_AS
		{
			get
			{
				return this._HEARING_AS;
			}
			set
			{
				if ((this._HEARING_AS != value))
				{
					this._HEARING_AS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONVERSATIONAL_AS", DbType="VarChar(254)")]
		public string CONVERSATIONAL_AS
		{
			get
			{
				return this._CONVERSATIONAL_AS;
			}
			set
			{
				if ((this._CONVERSATIONAL_AS != value))
				{
					this._CONVERSATIONAL_AS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEARING_RIGHT", DbType="VarChar(254)")]
		public string HEARING_RIGHT
		{
			get
			{
				return this._HEARING_RIGHT;
			}
			set
			{
				if ((this._HEARING_RIGHT != value))
				{
					this._HEARING_RIGHT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEARING_LEFT", DbType="VarChar(254)")]
		public string HEARING_LEFT
		{
			get
			{
				return this._HEARING_LEFT;
			}
			set
			{
				if ((this._HEARING_LEFT != value))
				{
					this._HEARING_LEFT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLARITY_OF_SPEECH", DbType="VarChar(254)")]
		public string CLARITY_OF_SPEECH
		{
			get
			{
				return this._CLARITY_OF_SPEECH;
			}
			set
			{
				if ((this._CLARITY_OF_SPEECH != value))
				{
					this._CLARITY_OF_SPEECH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BP_DIASTOLIC", DbType="VarChar(254)")]
		public string BP_DIASTOLIC
		{
			get
			{
				return this._BP_DIASTOLIC;
			}
			set
			{
				if ((this._BP_DIASTOLIC != value))
				{
					this._BP_DIASTOLIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RHYTHM", DbType="VarChar(254)")]
		public string RHYTHM
		{
			get
			{
				return this._RHYTHM;
			}
			set
			{
				if ((this._RHYTHM != value))
				{
					this._RHYTHM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_head_injury", DbType="VarChar(254)")]
		public string head_injury
		{
			get
			{
				return this._head_injury;
			}
			set
			{
				if ((this._head_injury != value))
				{
					this._head_injury = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frequent_headaches", DbType="VarChar(254)")]
		public string frequent_headaches
		{
			get
			{
				return this._frequent_headaches;
			}
			set
			{
				if ((this._frequent_headaches != value))
				{
					this._frequent_headaches = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frequent_dizziness", DbType="VarChar(254)")]
		public string frequent_dizziness
		{
			get
			{
				return this._frequent_dizziness;
			}
			set
			{
				if ((this._frequent_dizziness != value))
				{
					this._frequent_dizziness = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fainting_spells", DbType="VarChar(254)")]
		public string fainting_spells
		{
			get
			{
				return this._fainting_spells;
			}
			set
			{
				if ((this._fainting_spells != value))
				{
					this._fainting_spells = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insomnia", DbType="VarChar(254)")]
		public string insomnia
		{
			get
			{
				return this._insomnia;
			}
			set
			{
				if ((this._insomnia != value))
				{
					this._insomnia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depression", DbType="VarChar(254)")]
		public string depression
		{
			get
			{
				return this._depression;
			}
			set
			{
				if ((this._depression != value))
				{
					this._depression = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trachoma", DbType="VarChar(254)")]
		public string trachoma
		{
			get
			{
				return this._trachoma;
			}
			set
			{
				if ((this._trachoma != value))
				{
					this._trachoma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deafness", DbType="VarChar(254)")]
		public string deafness
		{
			get
			{
				return this._deafness;
			}
			set
			{
				if ((this._deafness != value))
				{
					this._deafness = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nose_throat_disorder", DbType="VarChar(254)")]
		public string nose_throat_disorder
		{
			get
			{
				return this._nose_throat_disorder;
			}
			set
			{
				if ((this._nose_throat_disorder != value))
				{
					this._nose_throat_disorder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tuberculosis", DbType="VarChar(254)")]
		public string tuberculosis
		{
			get
			{
				return this._tuberculosis;
			}
			set
			{
				if ((this._tuberculosis != value))
				{
					this._tuberculosis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other_lung_disorder", DbType="VarChar(254)")]
		public string other_lung_disorder
		{
			get
			{
				return this._other_lung_disorder;
			}
			set
			{
				if ((this._other_lung_disorder != value))
				{
					this._other_lung_disorder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_high_blood_pressure", DbType="VarChar(254)")]
		public string high_blood_pressure
		{
			get
			{
				return this._high_blood_pressure;
			}
			set
			{
				if ((this._high_blood_pressure != value))
				{
					this._high_blood_pressure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heart_disease", DbType="VarChar(254)")]
		public string heart_disease
		{
			get
			{
				return this._heart_disease;
			}
			set
			{
				if ((this._heart_disease != value))
				{
					this._heart_disease = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rheumatic_fever", DbType="VarChar(254)")]
		public string rheumatic_fever
		{
			get
			{
				return this._rheumatic_fever;
			}
			set
			{
				if ((this._rheumatic_fever != value))
				{
					this._rheumatic_fever = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diabetes_mellitus", DbType="VarChar(254)")]
		public string diabetes_mellitus
		{
			get
			{
				return this._diabetes_mellitus;
			}
			set
			{
				if ((this._diabetes_mellitus != value))
				{
					this._diabetes_mellitus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other_endocrine_disorder", DbType="VarChar(254)")]
		public string other_endocrine_disorder
		{
			get
			{
				return this._other_endocrine_disorder;
			}
			set
			{
				if ((this._other_endocrine_disorder != value))
				{
					this._other_endocrine_disorder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancer_tumor", DbType="VarChar(254)")]
		public string cancer_tumor
		{
			get
			{
				return this._cancer_tumor;
			}
			set
			{
				if ((this._cancer_tumor != value))
				{
					this._cancer_tumor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blood_disorders", DbType="VarChar(254)")]
		public string blood_disorders
		{
			get
			{
				return this._blood_disorders;
			}
			set
			{
				if ((this._blood_disorders != value))
				{
					this._blood_disorders = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stomach_pain", DbType="VarChar(254)")]
		public string stomach_pain
		{
			get
			{
				return this._stomach_pain;
			}
			set
			{
				if ((this._stomach_pain != value))
				{
					this._stomach_pain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other_abdominal_disorder", DbType="VarChar(254)")]
		public string other_abdominal_disorder
		{
			get
			{
				return this._other_abdominal_disorder;
			}
			set
			{
				if ((this._other_abdominal_disorder != value))
				{
					this._other_abdominal_disorder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kidney_bladder_disorder", DbType="VarChar(254)")]
		public string kidney_bladder_disorder
		{
			get
			{
				return this._kidney_bladder_disorder;
			}
			set
			{
				if ((this._kidney_bladder_disorder != value))
				{
					this._kidney_bladder_disorder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_back_injury", DbType="VarChar(254)")]
		public string back_injury
		{
			get
			{
				return this._back_injury;
			}
			set
			{
				if ((this._back_injury != value))
				{
					this._back_injury = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genetic_hereditary", DbType="VarChar(254)")]
		public string genetic_hereditary
		{
			get
			{
				return this._genetic_hereditary;
			}
			set
			{
				if ((this._genetic_hereditary != value))
				{
					this._genetic_hereditary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexually_transmit_disease", DbType="VarChar(254)")]
		public string sexually_transmit_disease
		{
			get
			{
				return this._sexually_transmit_disease;
			}
			set
			{
				if ((this._sexually_transmit_disease != value))
				{
					this._sexually_transmit_disease = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_asthma", DbType="VarChar(254)")]
		public string asthma
		{
			get
			{
				return this._asthma;
			}
			set
			{
				if ((this._asthma != value))
				{
					this._asthma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allergies", DbType="VarChar(254)")]
		public string allergies
		{
			get
			{
				return this._allergies;
			}
			set
			{
				if ((this._allergies != value))
				{
					this._allergies = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gynecological_disorder", DbType="VarChar(254)")]
		public string gynecological_disorder
		{
			get
			{
				return this._gynecological_disorder;
			}
			set
			{
				if ((this._gynecological_disorder != value))
				{
					this._gynecological_disorder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operations", DbType="VarChar(254)")]
		public string operations
		{
			get
			{
				return this._operations;
			}
			set
			{
				if ((this._operations != value))
				{
					this._operations = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operations_specify", DbType="VarChar(254)")]
		public string operations_specify
		{
			get
			{
				return this._operations_specify;
			}
			set
			{
				if ((this._operations_specify != value))
				{
					this._operations_specify = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schistosomiasis", DbType="VarChar(254)")]
		public string schistosomiasis
		{
			get
			{
				return this._schistosomiasis;
			}
			set
			{
				if ((this._schistosomiasis != value))
				{
					this._schistosomiasis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_menstrual_period", DbType="VarChar(254)")]
		public string last_menstrual_period
		{
			get
			{
				return this._last_menstrual_period;
			}
			set
			{
				if ((this._last_menstrual_period != value))
				{
					this._last_menstrual_period = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allergies_specify", DbType="VarChar(254)")]
		public string allergies_specify
		{
			get
			{
				return this._allergies_specify;
			}
			set
			{
				if ((this._allergies_specify != value))
				{
					this._allergies_specify = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other_abdominal_specify", DbType="VarChar(254)")]
		public string other_abdominal_specify
		{
			get
			{
				return this._other_abdominal_specify;
			}
			set
			{
				if ((this._other_abdominal_specify != value))
				{
					this._other_abdominal_specify = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column1", DbType="VarChar(254)")]
		public string column1
		{
			get
			{
				return this._column1;
			}
			set
			{
				if ((this._column1 != value))
				{
					this._column1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column2", DbType="VarChar(254)")]
		public string column2
		{
			get
			{
				return this._column2;
			}
			set
			{
				if ((this._column2 != value))
				{
					this._column2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column3", DbType="VarChar(254)")]
		public string column3
		{
			get
			{
				return this._column3;
			}
			set
			{
				if ((this._column3 != value))
				{
					this._column3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column4", DbType="VarChar(254)")]
		public string column4
		{
			get
			{
				return this._column4;
			}
			set
			{
				if ((this._column4 != value))
				{
					this._column4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column5", DbType="VarChar(254)")]
		public string column5
		{
			get
			{
				return this._column5;
			}
			set
			{
				if ((this._column5 != value))
				{
					this._column5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column6", DbType="VarChar(254)")]
		public string column6
		{
			get
			{
				return this._column6;
			}
			set
			{
				if ((this._column6 != value))
				{
					this._column6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column7", DbType="VarChar(254)")]
		public string column7
		{
			get
			{
				return this._column7;
			}
			set
			{
				if ((this._column7 != value))
				{
					this._column7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column7_comment", DbType="VarChar(254)")]
		public string column7_comment
		{
			get
			{
				return this._column7_comment;
			}
			set
			{
				if ((this._column7_comment != value))
				{
					this._column7_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column8", DbType="VarChar(254)")]
		public string column8
		{
			get
			{
				return this._column8;
			}
			set
			{
				if ((this._column8 != value))
				{
					this._column8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column8_comment", DbType="VarChar(254)")]
		public string column8_comment
		{
			get
			{
				return this._column8_comment;
			}
			set
			{
				if ((this._column8_comment != value))
				{
					this._column8_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column1_comment", DbType="VarChar(254)")]
		public string column1_comment
		{
			get
			{
				return this._column1_comment;
			}
			set
			{
				if ((this._column1_comment != value))
				{
					this._column1_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column2_comment", DbType="VarChar(254)")]
		public string column2_comment
		{
			get
			{
				return this._column2_comment;
			}
			set
			{
				if ((this._column2_comment != value))
				{
					this._column2_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column3_comment", DbType="VarChar(254)")]
		public string column3_comment
		{
			get
			{
				return this._column3_comment;
			}
			set
			{
				if ((this._column3_comment != value))
				{
					this._column3_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column4_comment", DbType="VarChar(254)")]
		public string column4_comment
		{
			get
			{
				return this._column4_comment;
			}
			set
			{
				if ((this._column4_comment != value))
				{
					this._column4_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column5_comment", DbType="VarChar(254)")]
		public string column5_comment
		{
			get
			{
				return this._column5_comment;
			}
			set
			{
				if ((this._column5_comment != value))
				{
					this._column5_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column6_comment", DbType="VarChar(254)")]
		public string column6_comment
		{
			get
			{
				return this._column6_comment;
			}
			set
			{
				if ((this._column6_comment != value))
				{
					this._column6_comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="VarChar(100)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this._country = value;
				}
			}
		}
	}
	
	public partial class sp_UserResult
	{
		
		private int _cn;
		
		private string _Fullname;
		
		private string _Username;
		
		private System.Nullable<bool> _Remark;
		
		private string _Description;
		
		public sp_UserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="VarChar(254)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(254)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="Bit")]
		public System.Nullable<bool> Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(254)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	public partial class CenterportAccounting_ProductListingResult
	{
		
		private long _RecID;
		
		private string _EmployerCode;
		
		private string _ItemCode;
		
		private string _ProductName;
		
		private string _ParentCode;
		
		private string _ParentDescription;
		
		private System.Nullable<int> _LevelCode;
		
		private string _LevelName;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<int> _Active;
		
		private string _EmployerName;
		
		public CenterportAccounting_ProductListingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecID", DbType="BigInt NOT NULL")]
		public long RecID
		{
			get
			{
				return this._RecID;
			}
			set
			{
				if ((this._RecID != value))
				{
					this._RecID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployerCode", DbType="VarChar(MAX)")]
		public string EmployerCode
		{
			get
			{
				return this._EmployerCode;
			}
			set
			{
				if ((this._EmployerCode != value))
				{
					this._EmployerCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCode", DbType="VarChar(MAX)")]
		public string ItemCode
		{
			get
			{
				return this._ItemCode;
			}
			set
			{
				if ((this._ItemCode != value))
				{
					this._ItemCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(MAX)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCode", DbType="VarChar(MAX)")]
		public string ParentCode
		{
			get
			{
				return this._ParentCode;
			}
			set
			{
				if ((this._ParentCode != value))
				{
					this._ParentCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentDescription", DbType="VarChar(MAX)")]
		public string ParentDescription
		{
			get
			{
				return this._ParentDescription;
			}
			set
			{
				if ((this._ParentDescription != value))
				{
					this._ParentDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelCode", DbType="Int")]
		public System.Nullable<int> LevelCode
		{
			get
			{
				return this._LevelCode;
			}
			set
			{
				if ((this._LevelCode != value))
				{
					this._LevelCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelName", DbType="VarChar(MAX)")]
		public string LevelName
		{
			get
			{
				return this._LevelName;
			}
			set
			{
				if ((this._LevelName != value))
				{
					this._LevelName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int")]
		public System.Nullable<int> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployerName", DbType="VarChar(MAX)")]
		public string EmployerName
		{
			get
			{
				return this._EmployerName;
			}
			set
			{
				if ((this._EmployerName != value))
				{
					this._EmployerName = value;
				}
			}
		}
	}
	
	public partial class sp_loginResult
	{
		
		private int _cn;
		
		private string _Fullname;
		
		private string _Username;
		
		private int _UserLevel;
		
		private bool _Remark;
		
		public sp_loginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="VarChar(254) NOT NULL", CanBeNull=false)]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(254) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLevel", DbType="Int NOT NULL")]
		public int UserLevel
		{
			get
			{
				return this._UserLevel;
			}
			set
			{
				if ((this._UserLevel != value))
				{
					this._UserLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="Bit NOT NULL")]
		public bool Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
	}
	
	public partial class USER_INSERTResult
	{
		
		private string _Column1;
		
		public USER_INSERTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class USER_UPDATEResult
	{
		
		private string _Column1;
		
		public USER_UPDATEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class MedicalPatientListResult
	{
		
		private int _cn;
		
		private string _papin;
		
		private string _PatientName;
		
		public MedicalPatientListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_papin", DbType="VarChar(50)")]
		public string papin
		{
			get
			{
				return this._papin;
			}
			set
			{
				if ((this._papin != value))
				{
					this._papin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="VarChar(153) NOT NULL", CanBeNull=false)]
		public string PatientName
		{
			get
			{
				return this._PatientName;
			}
			set
			{
				if ((this._PatientName != value))
				{
					this._PatientName = value;
				}
			}
		}
	}
	
	public partial class MedicalImmunologyTestSearchResult
	{
		
		private string _isFound;
		
		private int _RecId;
		
		private string _papin;
		
		private string _lastname;
		
		private string _firstname;
		
		private string _middlename;
		
		private string _gender;
		
		private string _birthdate;
		
		private string _employer;
		
		private string _position;
		
		private System.Nullable<int> _LaboratoryNo;
		
		private string _psa;
		
		private string _Other;
		
		private string _HBsAg;
		
		private string _RPR;
		
		private string _AntiHBS;
		
		private string _AntiHBSResult;
		
		private string _MedTech;
		
		private string _MedTechLicense;
		
		private string _Pathologist;
		
		private string _PathologistLicense;
		
		private System.Nullable<System.DateTime> _ResultDate;
		
		private string _otherName;
		
		private string _otherRefValue;
		
		private string _cutOff;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		public MedicalImmunologyTestSearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isFound", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string isFound
		{
			get
			{
				return this._isFound;
			}
			set
			{
				if ((this._isFound != value))
				{
					this._isFound = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecId", DbType="Int NOT NULL")]
		public int RecId
		{
			get
			{
				return this._RecId;
			}
			set
			{
				if ((this._RecId != value))
				{
					this._RecId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_papin", DbType="VarChar(50)")]
		public string papin
		{
			get
			{
				return this._papin;
			}
			set
			{
				if ((this._papin != value))
				{
					this._papin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="VarChar(50)")]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this._lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="VarChar(50)")]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this._firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middlename", DbType="VarChar(50)")]
		public string middlename
		{
			get
			{
				return this._middlename;
			}
			set
			{
				if ((this._middlename != value))
				{
					this._middlename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(10)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdate", DbType="VarChar(50)")]
		public string birthdate
		{
			get
			{
				return this._birthdate;
			}
			set
			{
				if ((this._birthdate != value))
				{
					this._birthdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employer", DbType="VarChar(50)")]
		public string employer
		{
			get
			{
				return this._employer;
			}
			set
			{
				if ((this._employer != value))
				{
					this._employer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(50)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this._position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaboratoryNo", DbType="Int")]
		public System.Nullable<int> LaboratoryNo
		{
			get
			{
				return this._LaboratoryNo;
			}
			set
			{
				if ((this._LaboratoryNo != value))
				{
					this._LaboratoryNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_psa", DbType="VarChar(100)")]
		public string psa
		{
			get
			{
				return this._psa;
			}
			set
			{
				if ((this._psa != value))
				{
					this._psa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="VarChar(100)")]
		public string Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this._Other = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HBsAg", DbType="VarChar(100)")]
		public string HBsAg
		{
			get
			{
				return this._HBsAg;
			}
			set
			{
				if ((this._HBsAg != value))
				{
					this._HBsAg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPR", DbType="VarChar(100)")]
		public string RPR
		{
			get
			{
				return this._RPR;
			}
			set
			{
				if ((this._RPR != value))
				{
					this._RPR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AntiHBS", DbType="VarChar(100)")]
		public string AntiHBS
		{
			get
			{
				return this._AntiHBS;
			}
			set
			{
				if ((this._AntiHBS != value))
				{
					this._AntiHBS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AntiHBSResult", DbType="VarChar(100)")]
		public string AntiHBSResult
		{
			get
			{
				return this._AntiHBSResult;
			}
			set
			{
				if ((this._AntiHBSResult != value))
				{
					this._AntiHBSResult = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedTech", DbType="VarChar(100)")]
		public string MedTech
		{
			get
			{
				return this._MedTech;
			}
			set
			{
				if ((this._MedTech != value))
				{
					this._MedTech = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedTechLicense", DbType="VarChar(50)")]
		public string MedTechLicense
		{
			get
			{
				return this._MedTechLicense;
			}
			set
			{
				if ((this._MedTechLicense != value))
				{
					this._MedTechLicense = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pathologist", DbType="VarChar(100)")]
		public string Pathologist
		{
			get
			{
				return this._Pathologist;
			}
			set
			{
				if ((this._Pathologist != value))
				{
					this._Pathologist = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PathologistLicense", DbType="VarChar(50)")]
		public string PathologistLicense
		{
			get
			{
				return this._PathologistLicense;
			}
			set
			{
				if ((this._PathologistLicense != value))
				{
					this._PathologistLicense = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> ResultDate
		{
			get
			{
				return this._ResultDate;
			}
			set
			{
				if ((this._ResultDate != value))
				{
					this._ResultDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherName", DbType="VarChar(20)")]
		public string otherName
		{
			get
			{
				return this._otherName;
			}
			set
			{
				if ((this._otherName != value))
				{
					this._otherName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherRefValue", DbType="VarChar(20)")]
		public string otherRefValue
		{
			get
			{
				return this._otherRefValue;
			}
			set
			{
				if ((this._otherRefValue != value))
				{
					this._otherRefValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cutOff", DbType="VarChar(20)")]
		public string cutOff
		{
			get
			{
				return this._cutOff;
			}
			set
			{
				if ((this._cutOff != value))
				{
					this._cutOff = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
